### ISSUE TITLE
Error in building for Ubuntu 15.04

### ISSUE THREAD

**Issue by GeorgeGkas** [cyberpython/lingua#11]
I have ubuntu 15.04 and I get the following build error.

```
Buildfile: /home/georgegks/glossa-interpreter-1.0.7/build.xml

load-properties-common:

load-properties-linux:

init:

set-build-type:

check-parser:
     [copy] Copying 1 file to /home/georgegks/glossa-interpreter-1.0.7/src/glossa/grammars

check-firts-pass-treeparser:
     [copy] Copying 1 file to /home/georgegks/glossa-interpreter-1.0.7/src/glossa/grammars

check-type-analyzer:
     [copy] Copying 1 file to /home/georgegks/glossa-interpreter-1.0.7/src/glossa/grammars

check-AST-interpreter:
     [copy] Copying 1 file to /home/georgegks/glossa-interpreter-1.0.7/src/glossa/grammars

check-antlr:

download-antlr:

generate-parser:

generate-firts-pass-treeparser:

generate-type-analyzer:

generate-AST-interpreter:

generate-parser-linux:

BUILD FAILED
/home/georgegks/glossa-interpreter-1.0.7/build.xml:175: Execute failed: java.io.IOException: Cannot run program "antlr3": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 23 more

Total time: 0 seconds
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 1
```
What should I do?

**Comment by GeorgeGkas** [comment]
I figure out. We need to follow that instructions : https://github.com/cyberpython/glossa-interpreter
